### ISSUE TITLE
Add option to return indices 

### ISSUE THREAD

**Issue by andrie** [robertdj/RDP#27]
I want to do some analysis where it's useful to compare the data in my original trajectory with the simplified trajectory.

To do this, I propose to create an argument called `keep_index`.  If this is TRUE, then return a data frame with `x`, `y` and `index`:

```R
> RamerDouglasPeucker(x, y, 5, keep_index = TRUE)
      x     y index
1   3.5 21.25     1
2  23.2  3.10     3
3  54.6 18.15     5
4  71.5  9.70     7
5 101.3 21.10     8
```

**Comment by robertdj** [comment]
I can also see that this makes sense, so happy to accept that functionality. Thanks for opening the PR -- I'll check it!
